### ISSUE TITLE
UiPath CLI version

### ISSUE THREAD

**Issue by michaelconan** [UiPath-Services/UiPath-DevOps-Scripts#4]
The latest release includes uipcli version 20.11.0-dev, which is well out of date and appears not to support the new Windows compatibility, which will soon be required in new versions. A new release should be created with the latest version ~22.10

**Comment by SE-Abdullah** [comment]
yes @michaelconan, the scripts will be upgraded soon with the new official uipath cli with version 22.10.**
https://docs.uipath.com/test-suite/docs/uipath-command-line-interface

**Comment by michaelconan** [comment]
Thanks @SE-Abdullah - do you have an estimate of when the update will occur? 
I checked the MyGet feed and do not see an updated version, and am unsure how to programmatically download from the official VS feed.

**Comment by SE-Abdullah** [comment]
> Thanks @SE-Abdullah - do you have an estimate of when the update will occur? I checked the MyGet feed and do not see an updated version, and am unsure how to programmatically download from the official VS feed.

This repo update will be released by mid next week. As for the official cli feed, you will find it here https://uipath.visualstudio.com/Public.Feeds/_artifacts/feed/UiPath-Official
Read more about it here https://docs.uipath.com/test-suite/docs/uipath-command-line-interface
